spring:
  application:
    name: consumer-som-feign
  zipkin:
#    service:
#      name: consumer-som-feign
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0  #默认采样比是0.1，即10%，生产环境请一定不要100%会死的 
server:
  port: 7901
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${myeureka.server.user.name}:${myeureka.server.user.password}@${myeureka.server.host}/eureka
      #defaultZone: http://zhangli:dev@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
#使用  /shutdown 来优雅关机    
endpoints:
  shutdown:
    enabled: true     #开启优雅关闭方式
    sensitive: false # 禁用密码验证
logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: debug