spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/a5535772/spring-cloud-config-repo
          search-paths: spring_cloud_config/config-demo2/*
          username: 214529283@qq.com
          password: Shljjoay8gljs
          default-label: master
server:
  port: 8888
  
