spring:
  application:
    name: microservice-spring-session-redis
  session:
    store-type: redis  #设置session存储类型为redis
  redis:
#    host: redis01.scm.test.baozun.cn
    host: 127.0.0.1
    port: 6379 
    database: 1
    password: 123456
server:
  port: 7901
