spring:
  application:
    name: microservice-gateway-zuul
server:
  port: 5555
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://zhangli:dev@localhost:8761/eureka  
zuul:
  routes:
    api-som-jd-node:
      path: /som/jd/**
      serviceId: user-provider
    api-som-tmall-node:
      path: /som/tmall/**
      url: http://10.88.77.143:7900/