spring:
  application:
    name: microservice-gateway-zuul
server:
  port: 5555
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://zhangli:dev@localhost:8761/eureka  
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
zuul:
  routes:
    api-som-jd-node:
      path: /som/jd/**
      serviceId: user-provider
    api-som-tmall-node:
      path: /som/tmall/**
      url: http://10.88.77.143:7900/      