spring:
  application:
    name: config-client
  cloud:
    config:
      uri: http://localhost:8888/
      label: master
      profile: pro
      name: consumer
      #name: consumer,provider
server:
  port: 8001
#安全设置，默认访问 /refresh需要spring-security的roll权限，这里进行了关闭
management:
  security:
    enabled: false