spring:
  application:
    name: mservice-mybatis
#  cloud:
#    config:
#      enabled: true #开启Config服务发现支持,默认为true
#      discovery:
#        service-id: config-server   #指定server端的name,也就是server端spring.application.name的值
##      uri: http://localhost:8888/
#      label: master
#      profile: pro
#      name: consumer
#      #name: consumer,provider
#      #username:使用用户名密码来访问 
#      #password: 
server:
  port: 8800
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG
#eureka:
#  client:
#    healthcheck:
#      enabled: true
#    serviceUrl:
#      defaultZone: http://zhangli:dev@localhost:8761/eureka
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}  