spring:
  application:
    name: user-provider

eureka:
  client:
    serviceUrl:
      defaultZone: http://${myeureka.server.user.name}:${myeureka.server.user.password}@${myeureka.server.host}/eureka
#      defaultZone: http://zhangli:dev@localhost:8761/eureka
#      defaultZone: http://${myeureka.server.user.name}:dev@${myeureka.server.host}/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
server:
  port: 7900          
#---
#server:
#  port: 7900
#spring:
#  profiles: port7900  
#---
#server:
#  port: 7901
#spring:
#  profiles: port7901
