spring:
  application:
    name: microservice-rabbitmq-hello
  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    #username: guest
    password: 123456
    #password: guest
server:
  port: 9100
#起不来 详见官方文档，不高兴配了