spring:
  application:
    name: microservice-rabbitmq-hello
  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    #username: guest
    password: 123456
    #指定虚拟机
    virtual-host: spring
server:
  port: 9100
