security:
  basic:
    enabled: true
#  这里写到配置文件啦！
#  user:
#    name: zhangli
#    password: 123456
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #defaultZone: http://zhangli:123456@localhost:8761/eureka
      defaultZone: http://${security.user.name}:${security.user.password}@localhost:8761/eureka
  server:
    enable-self-preservation: false #是否开启自我保护模式，生产中一定要开！